
evnt15 equ $
       ld a,1
       ld hl,numlif
       cp (hl)
       jp nz,p00189
       ld a,1
       call 8859
       ld a,5
       ld (23693),a
       ld (23695),a
       ld a,8
       ld (dispx),a
       ld a,8
       ld (dispy),a
       ld a,0
       call dmsg
       ld a,90
       ld b,a
       call delay
       ld a,4
       ld (numlif),a
       ld a,0
       ld (vara),a
       ld a,6
       ld (23693),a
       ld (23695),a
       ld a,20
       ld (dispx),a
       ld a,8
       ld (dispy),a
       ld a,(numlif)
       call disply
       ld a,0
       call addsc
       ld a,6
       ld (23693),a
       ld (23695),a
       ld a,20
       ld (dispx),a
       ld a,25
       ld (dispy),a
       call dscore
       ld hl,restfl
       ld (hl),h
p00189 ld a,1
       call 8859
       ld a,6
       ld (23693),a
       ld (23695),a
       ld a,20
       ld (dispx),a
       ld a,8
       ld (dispy),a
       ld a,(numlif)
       call disply
       ld a,2
       ld (23693),a
       ld (23695),a
       ld a,20
       ld (dispx),a
       ld a,1
       ld (dispy),a
       ld a,2
       call dmsg
       ld a,6
       ld (23693),a
       ld (23695),a
       ld a,20
       ld (dispx),a
       ld a,25
       ld (dispy),a
       call dscore
       ld a,2
       ld (23693),a
       ld (23695),a
       ld a,20
       ld (dispx),a
       ld a,19
       ld (dispy),a
       ld a,1
       call dmsg
       ld a,0
       call 8859
       ret