
evnt10 equ $
       ld a,0
       ld (vara),a
       ld a,6
       ld (23693),a
       ld (23695),a
       ld a,20
       ld (dispx),a
       ld a,8
       ld (dispy),a
       ld a,(numlif)
       call disply
       ld a,2
       ld (23693),a
       ld (23695),a
       ld a,20
       ld (dispx),a
       ld a,1
       ld (dispy),a
       ld a,2
       call dmsg
       ld a,6
       ld (23693),a
       ld (23695),a
       ld a,20
       ld (dispx),a
       ld a,25
       ld (dispy),a
       call dscore
       ld a,2
       ld (23693),a
       ld (23695),a
       ld a,20
       ld (dispx),a
       ld a,19
       ld (dispy),a
       ld a,1
       call dmsg
       ret